# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "tech blog // jared hirsch // ¯\\_(ツ)_/¯"
email: ohai@6a68.net
description: > # this means to ignore newlines until "baseurl:"
  tech blog // jared hirsch // ¯\_(ツ)_/¯
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://6a68.net" # the base hostname & protocol for your site
github_username:  jaredhirsch

mastodon:
- username: jaredhirsch
  instance: mastodon.social
- username: jaredhirsch
  instance: mathstodon.xyz

permalink: /:year/:title/

# Build settings
markdown: kramdown

# yay, Atom
gems:
  - jekyll-feed
